version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src/uploads:/var/www/html/uploads
    environment:
      - UPLOAD_MAX_FILESIZE=10M
      - POST_MAX_SIZE=10M